version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo install
  build:
    commands:
      - echo run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
